name: Build LeechAgent Linux

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build leechcore
        run: |
          cd leechcore
          make clean || true
          make

      - name: Build leechagent_linux
        run: |
          cd leechagent_linux
          make clean || true
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: leechagent-linux
          path: |
            leechagent_linux/leechagent
            leechcore/leechcore.so
